service: service 

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:

  list:
    handler: bin/list
    events:
      - http:
          path: list
          method: post
    environment:
      PLATFORM: aws_lambda

  compare:
    handler: bin/compare
    events:
      - http:
          path: compare
          method: post
    environment:
      PLATFORM: aws_lambda

  rank:
    handler: bin/rank
    events:
      - http:
          path: rank
          method: post
    environment:
      PLATFORM: aws_lambda